// examples/angular/v18/video-recruitment/src/components/video-recruitment/video-recruitment.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';

@Component({
	selector: 'app-video-recruitment',
	standalone: true,
	imports: [],
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	templateUrl: './video-recruitment.component.html',
})
export class VideoRecruitmentComponent {
	// Video Recruitment Widget Events
	handleFinishVideo(event: CustomEvent<boolean>) {
		const result = event;
		console.log('%c%s', 'color: #FFA500;', '[VIDEO RECRUITMENT] FinishVideo: ', result);
		console.log(event);
	}

	handleUserCancel(event: Event) {
		const result = event;
		console.log('%c%s', 'color: #FFA500;', '[VIDEO RECRUITMENT] UserCancel: ', result);
	}

	handleErrorException(event: any) {
		const result = event;
		console.log('%c%s', 'color: #FFA500;', '[VIDEO RECRUITMENT] ErrorException: ', result);
	}
}

<facephi-video-recruitment-widget
    full-screen
    language="es"

    (finishVideo)="onFinishVideo($event)"
    (userCancel)="onUserCancel($event)"
/>

// examples/next/V12/sdk-video-recruitment/components/VideoRecruitment-component/VideoRecruitment.component.tsx
'use client';
import { FacephiVideoRecruitmentWidget } from '@facephi/sdk-web-react';

export default function VideoRecluiment() {
	// Video Recruitment Widget Events
	function handleFinishVideo(event: CustomEvent<boolean>) {
		const result = event;
		console.log('%c%s', 'color: #FFA500;', '[VIDEO RECRUITMENT] FinishVideo: ', result);
	}

	function handleUserCancel(event: Event) {
		const result = event;
		console.log('%c%s', 'color: #FFA500;', '[VIDEO RECRUITMENT] UserCancel: ', result);
	}

	function handleErrorException(event: any) {
		const result = event;
		console.log('%c%s', 'color: #FFA500;', '[VIDEO RECRUITMENT] ErrorException: ', result);
	}

	return (
		<FacephiVideoRecruitmentWidget
			fullScreen={true}
			language='es'
			onFinishVideo={handleFinishVideo}
			onUserCancel={handleUserCancel}
			onErrorException={handleErrorException}
		/>
	);
}
