// examples/lit/storybook/src/main.js
import { defineCustomElements } from '@facephi/sdk-web-wc/bundle/';
import { SdkWrapper } from './SdkWrapper.js';

async function initializeApp() {
  try {
   
    defineCustomElements(window);
    
    await customElements.whenDefined('facephi-sdk-provider');
    
    if (!customElements.get('sdk-wrapper')) {
      customElements.define('sdk-wrapper', SdkWrapper);
      
    }
    
    if (document.readyState === 'loading') {
      await new Promise(resolve => {
        document.addEventListener('DOMContentLoaded', resolve);
      });
    }
          
    const appElement = document.getElementById('app');
    
    if (appElement) {
      appElement.innerHTML = '<sdk-wrapper></sdk-wrapper>';

    } else {
      const newAppElement = document.createElement('div');
      newAppElement.id = 'app';
      document.body.appendChild(newAppElement);
      newAppElement.innerHTML = '<sdk-wrapper></sdk-wrapper>';
    }

    const copyrightYearElement = document.getElementById('copyright-year');
    if (copyrightYearElement) {
      copyrightYearElement.insertAdjacentHTML('afterbegin', new Date().getFullYear());
    }
    
  } catch (error) {
    console.error('ERROR:', error);
  }
}

initializeApp();

// examples/react/react-19-cra/sdk-onboarding/src/index.tsx
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

import { defineCustomElements } from '@facephi/sdk-web-wc/loader';

function setCopyrightYear(elementId = 'copyright-year') {
	try {
		const element = document.getElementById(elementId);
		if (!element) {
			throw new Error(`Element with id '${elementId}' not found`);
		}
		element.insertAdjacentHTML('afterbegin', new Date().getFullYear().toString());
	} catch (error) {
		console.error('Failed to set copyright year:', error);
	}
}

setCopyrightYear();

createRoot(document.getElementById('app')!).render(
	<StrictMode>
		<App />
	</StrictMode>,
);

defineCustomElements(window);
