// examples/react/react-19-cra/sdk-react-onboarding/src/components/SelphIDComponent.tsx
import { FacephiSelphidWidget } from '@facephi/sdk-web-react';
import {
	type CodeReader,
	SelphidWidgetLoadedEvent,
	FacephiSelphidWidgetCustomEvent,
	SelphidExtractionFinishEvent,
	SelphidExtractionTimeoutEvent,
	SelphidExceptionCapturedEvent,
	SelphidErrorTimeoutEvent,
	SelphidTimeoutButtonClickEvent,
	SelphidUserCancelEvent,
	SelphidTrackStatusEvent,
} from '@facephi/sdk-web-wc';
import { Logger, LoggerType } from '../utils/Logger';

export default function SelphIDComponent({ setWidget }: { setWidget: React.Dispatch<React.SetStateAction<string>> }) {
	function handleModuleLoaded(event: FacephiSelphidWidgetCustomEvent<SelphidWidgetLoadedEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'widgetLoaded', result);
	}

	function handleExtractionFinish(event: FacephiSelphidWidgetCustomEvent<SelphidExtractionFinishEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'extractionFinish', result);
		// Redirect to Selphi
		setWidget('selphi');
	}

	function handleExtractionTimeout(event: FacephiSelphidWidgetCustomEvent<SelphidExtractionTimeoutEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'extractionTimeout', result);
	}

	function handleExceptionCaptured(event: FacephiSelphidWidgetCustomEvent<SelphidExceptionCapturedEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'exceptionCaptured', result);
	}

	function handleTimeoutButtonClick(event: FacephiSelphidWidgetCustomEvent<SelphidTimeoutButtonClickEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'timeoutButtonClick', result);
	}

	function handleErrorTimeout(event: FacephiSelphidWidgetCustomEvent<SelphidErrorTimeoutEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'errorTimeout', result);
	}

	function handleTrackStatus(event: FacephiSelphidWidgetCustomEvent<SelphidTrackStatusEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'trackStatus', result);
	}

	function handleUserCancel(event: FacephiSelphidWidgetCustomEvent<SelphidUserCancelEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'userCancel', result);
	}

	return (
		<FacephiSelphidWidget
			country={'ES'}
			previewImage={true}
			captureTimeout={10}
			captureRetries={3}
			showLog={false}
			codeReader={'off' as CodeReader}
			onModuleLoaded={handleModuleLoaded}
			onExtractionFinish={handleExtractionFinish}
			onExtractionTimeout={handleExtractionTimeout}
			onExceptionCaptured={handleExceptionCaptured}
			onErrorTimeout={handleErrorTimeout}
			onTimeoutErrorButtonClick={handleTimeoutButtonClick}
			onTrackStatus={handleTrackStatus}
			onUserCancel={handleUserCancel}
		/>
	);
}

// examples/angular/v19/sdk-angular-onboarding-ssr/src/components/selphid-component/selphid.component.ts
import { Component, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Logger, LoggerType } from '../../utils/Logger';
import { FacephiSelphidWidget } from '@facephi/sdk-web-angular';
import type {
	CodeReader,
	SelphidWidgetLoadedEvent,
	FacephiSelphidWidgetCustomEvent,
	SelphidExtractionFinishEvent,
	SelphidExtractionTimeoutEvent,
	SelphidExceptionCapturedEvent,
	SelphidErrorTimeoutEvent,
	SelphidTimeoutButtonClickEvent,
	SelphidUserCancelEvent,
	SelphidTrackStatusEvent,
} from '@facephi/sdk-web-wc';

@Component({
	selector: 'selphid-component',
	standalone: true,
	imports: [FacephiSelphidWidget],
	schemas: [],
	templateUrl: './selphid.component.html',
	styleUrl: './selphid.component.css',
})
export class SelphIDComponent {
	// Router to redirect to Selphi when finished
	router = inject(Router);
	currentRoute = inject(ActivatedRoute);

	// SelphID data
	selphid = {
		country: 'ES',
		previewImage: true,
		captureTimeout: 10,
		captureRetries: 3,
		showLog: false,
		codeReader: 'off' as CodeReader,
	};

	// SelphID Events
	handleModuleLoaded(event: CustomEvent<SelphidWidgetLoadedEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'widgetLoaded', result);
	}

	handleExtractionFinish(event: CustomEvent) {
		const result = event.detail.detail;

		Logger.printLog(LoggerType.SELPHID, 'extractionFinish', result);
		// Redirect to Selphi
		this.router.navigate(['../selphi'], { relativeTo: this.currentRoute });
	}

	handleExtractionTimeout(event: CustomEvent) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'extractionTimeout', result);
	}

	handleExceptionCaptured(event: CustomEvent<SelphidExceptionCapturedEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'exceptionCaptured', result);
	}

	handleErrorTimeout(event: CustomEvent<SelphidErrorTimeoutEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'errorTimeout', result);
	}

	handleTimeoutErrorButtonClick(event: CustomEvent<SelphidTimeoutButtonClickEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'timeoutErrorButtonClick', result);
	}

	handleUserCancel(event: CustomEvent<SelphidUserCancelEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'userCancel', result);
	}

	handleTrackStatus(event: CustomEvent<SelphidTrackStatusEvent>) {
		const result = event.detail.detail;
		Logger.printLog(LoggerType.SELPHID, 'trackStatus', result);
	}
}
